on:
  issue_comment:
    types: [created, edited]

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      # - name: invoke action
      #   uses: ./.github/actions/invoke-pwsh
      #   env:
      #     SAMPLE_ENV_1: ${{ github.ref }}
      #     sample_env_2: ${{ github.sha }}
      #     sampleEnv3: ${{ toJson(steps) }}
      #   with:
      #     foo: bar
      #     bar: 99

      - name: invoke action again
        uses: ebekker/test-github-actions-and-repo/.github/actions/invoke-pwsh@master
        env:
          SAMPLE_ENV_1: ${{ github.ref }}
          sample_env_2: ${{ github.sha }}
          sampleEnv3: ${{ toJson(steps) }}
        with:
          foo: bar
          bar: 99
          list_files: 1
      
      - name: upload list_files
        uses: actions/upload-artifact@v1
        with:
          name: list_files
          path: list_files
